version: '3.0'
services:
  service1:
    command: /api.yml
    image: danielgtaylor/apisprout:1.3.0
    volumes:
      - './openapi-service1.yml:/api.yml'
  service2:
    command: /api.yml
    image: danielgtaylor/apisprout:1.3.0
    volumes:
      - './openapi-service2.yml:/api.yml'
  gateway:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
  gateway-test:
    build:
      context: .
      dockerfile: gateway-test.dockerfile
